version: '3.8'

services:
  inventory-pos:
    build:
      context: ./apps/inventory-pos
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - REACT_APP_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - REACT_APP_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - REACT_APP_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - REACT_APP_FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - REACT_APP_LOYVERSE_API_KEY=${LOYVERSE_API_KEY}
    volumes:
      - ./apps/inventory-pos:/app
      - /app/node_modules
    networks:
      - bakery-network

  recipe-calculator:
    build:
      context: ./apps/recipe-calculator
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/recipe-calculator:/app
      - /app/node_modules
    networks:
      - bakery-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - inventory-pos
      - recipe-calculator
    networks:
      - bakery-network

networks:
  bakery-network:
    driver: bridge

# Note: Create Dockerfile.dev in each app directory
# Example for inventory-pos/Dockerfile.dev:
# FROM node:16-alpine
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# EXPOSE 3000
# CMD ["npm", "start"]

# Example for recipe-calculator/Dockerfile.dev:
# FROM node:16-alpine
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# EXPOSE 3000
# CMD ["npm", "run", "dev"]
